maintainer       "YOUR_COMPANY_NAME"
maintainer_email "YOUR_EMAIL"
license          "All rights reserved"
description      "Installs/Configures scribe"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends "boost"
depends "python"
depends "thrift"
depends "java"
depends "ant"
depends "hadoop"
depends "git"
depends "maven"
depends "mercurial"