maintainer       "Fletcher Nichol"
maintainer_email "fnichol@nichol.ca"
license          "Apache 2.0"
description      "Installs/Configures gitorious"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1"
depends          "rvm"
depends			 "mysql"
depends			 "nginx"
depends          "database"
depends          "imagemagick"
depends          "activemq"
depends			 "stompserver"
depends			 "sphinx"
depends			 "zlib"
depends			 "xml"
depends			 "git"